export interface FighterDisplayState {
  name: string;
  health: number;
  maxHealth: number;
  damage: number;
  stocks?: number;
  ultimateMeter?: number;
}

export type FighterState =
  | 'idle'
  | 'walk'
  | 'run'
  | 'dash'
  | 'crouch'
  | 'jump_squat'
  | 'jumping'
  | 'falling'
  | 'landing'
  | 'air_dodge'
  | 'jab'
  | 'jab_2'
  | 'jab_3'
  | 'tilt_forward'
  | 'tilt_up'
  | 'tilt_down'
  | 'smash_forward'
  | 'smash_up'
  | 'smash_down'
  | 'nair'
  | 'fair'
  | 'bair'
  | 'uair'
  | 'dair'
  | 'neutral_special'
  | 'side_special'
  | 'up_special'
  | 'down_special'
  | 'block'
  | 'parry'
  | 'dodge'
  | 'hitstun'
  | 'knockback'
  | 'tumble'
  | 'grab'
  | 'throw_forward'
  | 'throw_back'
  | 'ultimate'
  | 'victory'
  | 'defeat';
