/**
 * ULTIMATE ENTERTAINMENT ENTERPRISES PRESENTS
 * BEAST WARS STORY MODE
 * 30 Cinematic Missions — Marvel Ultimate Alliance meets Super Smash Bros meets Zootopia meets Spider-Man/Batman/Ninja Turtles
 * 
 * Experience the legendary story as you fight through the action!
 */

export interface StoryMission {
  id: string;
  actNumber: 1 | 2 | 3;
  missionNumber: number;
  name: string;
  description: string;
  cinematicIntro?: string;
  cinematicOutro?: string;
  objectives: string[];
  difficulty: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;
  bossName?: string;
  bossPhases?: number;
  arena: string;
  requiredCharacters?: string[];
  unlockableCharacters?: string[];
  storyBeat: string; // What happens in the story
  rewards: { xp: number; currency: number; loot: string[]; unlocks?: string[] };
  gameplayType: 'combat' | 'platforming' | 'stealth' | 'chase' | 'boss' | 'team' | 'survival';
}

// ============ ACT I: CONVERGENCE (Missions 1-10) ============
export const ACT_I_STORY_MISSIONS: StoryMission[] = [
  {
    id: 'story_act1_m1',
    actNumber: 1,
    missionNumber: 1,
    name: 'The Grand Tournament Begins',
    description: 'Radiant Jumper enters the Cross Point Arena. The crowd roars. But something feels wrong...',
    cinematicIntro: 'The arena lights blaze. Champions from across dimensions gather. Radiant Jumper steps into the spotlight.',
    objectives: ['Win your first match', 'Land 3 perfect dodges', 'Experience the arena atmosphere'],
    difficulty: 1,
    arena: 'cross_point_arena',
    requiredCharacters: ['radiant-jumper'],
    storyBeat: 'Radiant Jumper debuts. The tournament begins with high energy, but strange glitches appear.',
    rewards: { xp: 200, currency: 150, loot: ['Arena Badge'], unlocks: ['kaison'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act1_m2',
    actNumber: 1,
    missionNumber: 2,
    name: 'Kaison: The Swift Guardian Arrives',
    description: 'Kaison enters the tournament. His fox-wolf hybrid form moves with precision. But his past haunts him.',
    cinematicIntro: 'Kaison arrives, tactical jacket flowing. He remembers his lost mentor. The tournament is his chance to prove himself.',
    objectives: ['Master Fox Dash', 'Use web control 3 times', 'Win without taking damage'],
    difficulty: 2,
    arena: 'cross_point_arena',
    requiredCharacters: ['kaison'],
    storyBeat: 'Kaison debuts. His tactical skills shine, but survivor\'s guilt weighs heavy.',
    rewards: { xp: 250, currency: 200, loot: ['Tactical Crest'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act1_m3',
    actNumber: 1,
    missionNumber: 3,
    name: 'The Broken Bracket',
    description: 'The tournament bracket glitches. Reality tears. Void creatures pour through. This is no longer a game.',
    cinematicIntro: 'The screen flickers. The bracket shatters. A Rift tears open. Void beasts emerge. The tournament becomes a battlefield.',
    objectives: ['Defeat 5 Void Grunts', 'Close the Rift', 'Survive the chaos'],
    difficulty: 3,
    arena: 'cross_point_arena',
    bossName: 'Rift Warden',
    bossPhases: 2,
    storyBeat: 'INCITING INCIDENT: The tournament is invaded. Reality is under attack. Heroes must unite.',
    rewards: { xp: 300, currency: 250, loot: ['Rift Fragment'], unlocks: ['jaxon'] },
    gameplayType: 'survival',
  },
  {
    id: 'story_act1_m4',
    actNumber: 1,
    missionNumber: 4,
    name: 'Jaxon: Speed of Chaos',
    description: 'Jaxon bursts onto the scene. His electric quills crackle. Speed solves everything—or so he thinks.',
    cinematicIntro: 'Jaxon arrives in a blur. His isolation breaks. For the first time, he\'s not alone—he\'s needed.',
    objectives: ['Chain 5 speed attacks', 'Use Spin Dash 3 times', 'Win with style'],
    difficulty: 2,
    arena: 'emerald_frontier',
    requiredCharacters: ['jaxon'],
    storyBeat: 'Jaxon debuts. His speed is unmatched, but he learns speed alone isn\'t enough.',
    rewards: { xp: 250, currency: 200, loot: ['Speed Gem'] },
    gameplayType: 'chase',
  },
  {
    id: 'story_act1_m5',
    actNumber: 1,
    missionNumber: 5,
    name: 'City Under Siege',
    description: 'The Bronx streets become a warzone. Beast-hybrids fight side-by-side. Zootopia meets Marvel Ultimate Alliance.',
    cinematicIntro: 'The city erupts. Civilians flee. Beast-hybrids emerge from alleys. Heroes and citizens unite.',
    objectives: ['Protect 10 civilians', 'Defeat 8 Void Grunts', 'Clear the district'],
    difficulty: 4,
    arena: 'bronx_streets',
    storyBeat: 'City defense begins. Heroes realize the scope of the invasion. Unity is essential.',
    rewards: { xp: 350, currency: 300, loot: ['City Defender Badge'] },
    gameplayType: 'team',
  },
  {
    id: 'story_act1_m6',
    actNumber: 1,
    missionNumber: 6,
    name: 'Kaison vs Jaxon: Rivalry Ignited',
    description: 'Two legends clash. Kaison\'s tactics vs Jaxon\'s speed. But they must learn to work together.',
    cinematicIntro: 'They meet in the arena. Different styles. Different wounds. But the same goal: protect the innocent.',
    objectives: ['Fight to a draw', 'Learn each other\'s moves', 'Form a temporary alliance'],
    difficulty: 3,
    arena: 'cross_point_arena',
    requiredCharacters: ['kaison', 'jaxon'],
    storyBeat: 'Kaison and Jaxon clash, then unite. Their rivalry becomes respect. The foundation for fusion begins.',
    rewards: { xp: 300, currency: 250, loot: ['Rivalry Crest'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act1_m7',
    actNumber: 1,
    missionNumber: 7,
    name: 'Silver: The Time Fixer',
    description: 'Silver arrives. Time itself bends. He sees the death loops. He must prevent catastrophe.',
    cinematicIntro: 'Time freezes. Silver steps through. He sees Radiant Jumper\'s death loop. He must intervene.',
    objectives: ['Use time manipulation', 'Prevent a death loop', 'Stabilize the timeline'],
    difficulty: 4,
    arena: 'memory_nexus',
    requiredCharacters: ['silver'],
    unlockableCharacters: ['silver'],
    storyBeat: 'Silver reveals the timeline is fracturing. Death loops threaten reality. He becomes a mentor.',
    rewards: { xp: 400, currency: 350, loot: ['Time Shard'], unlocks: ['silver'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act1_m8',
    actNumber: 1,
    missionNumber: 8,
    name: 'The Emerald Frontier Chase',
    description: 'Speed trials on momentum lanes. Loop-de-loops. A chase through impossible geometry. Spider-Man meets Sonic.',
    cinematicIntro: 'The Emerald Frontier opens. Momentum lanes twist through reality. A high-speed chase begins.',
    objectives: ['Complete the speed trial', 'Hit all momentum lanes', 'Catch the Void Runner'],
    difficulty: 5,
    arena: 'emerald_frontier',
    storyBeat: 'Speed trial reveals the heroes\' potential. Momentum becomes a weapon. The chase is on.',
    rewards: { xp: 450, currency: 400, loot: ['Momentum Ring'] },
    gameplayType: 'chase',
  },
  {
    id: 'story_act1_m9',
    actNumber: 1,
    missionNumber: 9,
    name: 'Lunara: The Harmony Anchor',
    description: 'Lunara appears. Her healing resonance soothes. She hears unborn Kai-Jax crying in the Weave.',
    cinematicIntro: 'Harmony pulses through the battlefield. Lunara arrives. She senses something new—something powerful—being born.',
    objectives: ['Heal 3 allies', 'Use Harmony Resonance', 'Protect Lunara'],
    difficulty: 3,
    arena: 'memory_nexus',
    requiredCharacters: ['lunara'],
    unlockableCharacters: ['lunara'],
    storyBeat: 'Lunara joins. She senses Kai-Jax before he exists. The Triad begins to form.',
    rewards: { xp: 350, currency: 300, loot: ['Harmony Gem'], unlocks: ['lunara'] },
    gameplayType: 'team',
  },
  {
    id: 'story_act1_m10',
    actNumber: 1,
    missionNumber: 10,
    name: 'First Kai-Jax Echo',
    description: 'A memory echo appears. Three tails. Gold, blue, white. Kai-Jax exists in the future—and the past.',
    cinematicIntro: 'The Weave shimmers. An echo forms. Three tails materialize. Gold, blue, white. The Memory Hero appears—briefly.',
    objectives: ['Witness the echo', 'Learn from the future', 'Prepare for fusion'],
    difficulty: 6,
    arena: 'memory_nexus',
    bossName: 'Echo Guardian',
    bossPhases: 1,
    storyBeat: 'MIDPOINT: Kai-Jax echo appears. The future is written. Heroes must make it happen.',
    rewards: { xp: 500, currency: 450, loot: ['Echo Fragment'], unlocks: ['kai-jax'] },
    gameplayType: 'boss',
  },
];

// ============ ACT II: FRACTURED LIGHT (Missions 11-20) ============
export const ACT_II_STORY_MISSIONS: StoryMission[] = [
  {
    id: 'story_act2_m1',
    actNumber: 2,
    missionNumber: 11,
    name: 'Six Months Later: Scattered',
    description: 'The heroes are scattered. Hunted. Desperate. The Void has won ground. Hope is fading.',
    cinematicIntro: 'Six months pass. The heroes are on the run. Safe zones shrink. The Void spreads. But they fight on.',
    objectives: ['Survive the ambush', 'Regroup with allies', 'Find a safe zone'],
    difficulty: 5,
    arena: 'bronx_streets',
    storyBeat: 'Time jump. Heroes are scattered. The war has escalated. Unity is harder than ever.',
    rewards: { xp: 400, currency: 350, loot: ['Survivor Badge'] },
    gameplayType: 'survival',
  },
  {
    id: 'story_act2_m2',
    actNumber: 2,
    missionNumber: 12,
    name: 'The Last Stand Defense',
    description: 'One final stronghold. Heroes make their stand. Batman-style tactical defense meets Marvel team-up.',
    cinematicIntro: 'The last safe zone. Void forces mass. Heroes prepare. This is it—win or lose everything.',
    objectives: ['Defend for 5 minutes', 'Protect the stronghold', 'Hold the line'],
    difficulty: 7,
    arena: 'nexus_haven',
    storyBeat: 'ROCK BOTTOM: Last stand. Heroes pushed to the limit. Desperation breeds innovation.',
    rewards: { xp: 600, currency: 500, loot: ['Last Stand Medal'] },
    gameplayType: 'survival',
  },
  {
    id: 'story_act2_m3',
    actNumber: 2,
    missionNumber: 13,
    name: 'Cobalt Blur: Speed Legend',
    description: 'Cobalt Blur arrives. The speed legend. He trains Kaison and Jaxon. Speed becomes art.',
    cinematicIntro: 'A blur. Cobalt Blur appears. He\'s seen it all. Now he teaches the next generation.',
    objectives: ['Learn Chaos Control', 'Master speed techniques', 'Prove your worth'],
    difficulty: 4,
    arena: 'emerald_frontier',
    requiredCharacters: ['cobalt-blur'],
    unlockableCharacters: ['cobalt-blur'],
    storyBeat: 'Cobalt Blur mentors. Speed becomes more than movement—it becomes control.',
    rewards: { xp: 450, currency: 400, loot: ['Speed Master Badge'], unlocks: ['cobalt-blur'] },
    gameplayType: 'chase',
  },
  {
    id: 'story_act2_m4',
    actNumber: 2,
    missionNumber: 14,
    name: 'The Skyforge Climb',
    description: 'Vertical challenge. Climbable towers. Storm clouds. Ninja Turtles-style platforming meets Batman traversal.',
    cinematicIntro: 'The Skyforge rises. Towers pierce storm clouds. Heroes must climb. The Void waits above.',
    objectives: ['Climb to the summit', 'Avoid storm strikes', 'Reach the peak'],
    difficulty: 6,
    arena: 'skyforge_plateau',
    storyBeat: 'Vertical challenge. Heroes prove their determination. The climb is the test.',
    rewards: { xp: 500, currency: 450, loot: ['Skyforge Crest'] },
    gameplayType: 'platforming',
  },
  {
    id: 'story_act2_m5',
    actNumber: 2,
    missionNumber: 15,
    name: 'The First Fusion: Kai-Jax Born',
    description: 'Kaison and Jaxon fuse. Three tails emerge. Gold, blue, white. Kai-Jax is born. The Memory Hero awakens.',
    cinematicIntro: 'They stand together. Synergy meter fills. 100%. The fusion begins. Three tails emerge. Kai-Jax is born.',
    objectives: ['Achieve 100% synergy', 'Fuse into Kai-Jax', 'Master the three tails'],
    difficulty: 8,
    arena: 'memory_nexus',
    requiredCharacters: ['kaison', 'jaxon'],
    storyBeat: 'MIDPOINT: First fusion. Kai-Jax is born. The Memory Hero awakens. Everything changes.',
    rewards: { xp: 800, currency: 700, loot: ['Fusion Core'], unlocks: ['kai-jax'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act2_m6',
    actNumber: 2,
    missionNumber: 16,
    name: 'Kai-Jax: Memory Echo Dive',
    description: 'Kai-Jax dives into memories. Past battles replay. He learns from fallen heroes. Memory is power.',
    cinematicIntro: 'Kai-Jax closes his eyes. The Weave opens. Memories flood in. Past battles. Fallen heroes. He learns.',
    objectives: ['Dive into 3 memories', 'Learn from echoes', 'Master Memory Dive'],
    difficulty: 5,
    arena: 'memory_nexus',
    requiredCharacters: ['kai-jax'],
    storyBeat: 'Kai-Jax masters memory magic. He can relive the past. Learn from the fallen.',
    rewards: { xp: 550, currency: 500, loot: ['Memory Shard'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act2_m7',
    actNumber: 2,
    missionNumber: 17,
    name: 'Prison Break: Free the Captured',
    description: 'Void prison. Heroes captured. Stealth mission. Batman-style infiltration meets Ninja Turtles teamwork.',
    cinematicIntro: 'The Void prison looms. Heroes are inside. Time for a rescue. Stealth and teamwork required.',
    objectives: ['Infiltrate the prison', 'Free 5 captured heroes', 'Escape without detection'],
    difficulty: 6,
    arena: 'rift_citadel',
    storyBeat: 'Prison break. Heroes rescue allies. The team grows. Unity strengthens.',
    rewards: { xp: 600, currency: 550, loot: ['Liberator Badge'] },
    gameplayType: 'stealth',
  },
  {
    id: 'story_act2_m8',
    actNumber: 2,
    missionNumber: 18,
    name: 'The Rift Generals: Void Tower Warden',
    description: 'First Rift General. Shield-based fortress. Tactical battle. Marvel Ultimate Alliance boss fight.',
    cinematicIntro: 'The Void Tower rises. The Warden guards it. Shield-based defense. Heroes must break through.',
    objectives: ['Break the shield', 'Defeat the Warden', 'Claim the tower'],
    difficulty: 7,
    arena: 'void_tower',
    bossName: 'Void Tower Warden',
    bossPhases: 3,
    storyBeat: 'First Rift General falls. Progress. The Void weakens. Hope returns.',
    rewards: { xp: 700, currency: 600, loot: ['Warden\'s Shield'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act2_m9',
    actNumber: 2,
    missionNumber: 19,
    name: 'Team Unified: The Triad Forms',
    description: 'Silver, Lunara, and Kai-Jax unite. The Triad forms. Harmony, Time, and Memory combine.',
    cinematicIntro: 'Three stand together. Silver (Time). Lunara (Harmony). Kai-Jax (Memory). The Triad forms.',
    objectives: ['Form the Triad', 'Use combined powers', 'Stabilize a Rift'],
    difficulty: 6,
    arena: 'memory_nexus',
    requiredCharacters: ['silver', 'lunara', 'kai-jax'],
    storyBeat: 'The Triad forms. Three powers unite. Reality stabilizes. The team is complete.',
    rewards: { xp: 650, currency: 600, loot: ['Triad Crest'] },
    gameplayType: 'team',
  },
  {
    id: 'story_act2_m10',
    actNumber: 2,
    missionNumber: 20,
    name: 'Mission Clear: The Path Forward',
    description: 'The team is unified. The mission is clear. The Rift Citadel awaits. The final assault begins.',
    cinematicIntro: 'The team stands ready. Mission clear. The Rift Citadel awaits. The final assault begins.',
    objectives: ['Unite all heroes', 'Plan the assault', 'Prepare for war'],
    difficulty: 7,
    arena: 'nexus_haven',
    storyBeat: 'CLIMAX: Team unified. Mission clear. The final assault on the Rift Citadel begins.',
    rewards: { xp: 750, currency: 700, loot: ['Unity Medal'] },
    gameplayType: 'team',
  },
];

// ============ ACT III: UNITY'S DAWN (Missions 21-30) ============
export const ACT_III_STORY_MISSIONS: StoryMission[] = [
  {
    id: 'story_act3_m1',
    actNumber: 3,
    missionNumber: 21,
    name: 'The Rift Citadel Siege',
    description: 'The mobile fortress. Multi-stage siege. Marvel Ultimate Alliance scale. Heroes assault the Citadel.',
    cinematicIntro: 'The Rift Citadel looms. Mobile fortress. Multi-stage siege. Heroes charge. The final battle begins.',
    objectives: ['Breach the outer wall', 'Fight through 3 stages', 'Reach the inner sanctum'],
    difficulty: 8,
    arena: 'rift_citadel',
    storyBeat: 'The siege begins. Heroes assault the Citadel. Stage by stage, they advance.',
    rewards: { xp: 800, currency: 750, loot: ['Siege Badge'] },
    gameplayType: 'team',
  },
  {
    id: 'story_act3_m2',
    actNumber: 3,
    missionNumber: 22,
    name: 'Rift Harvester: Archipelago Terror',
    description: 'Second Rift General. Life-draining archipelago. Zootopia-style environment. Epic boss battle.',
    cinematicIntro: 'The archipelago. The Harvester drains life. Heroes must fight on water, land, and air.',
    objectives: ['Survive the life drain', 'Defeat the Harvester', 'Restore the archipelago'],
    difficulty: 8,
    arena: 'archipelago',
    bossName: 'Rift Harvester',
    bossPhases: 4,
    storyBeat: 'Second Rift General falls. The archipelago is saved. Heroes advance.',
    rewards: { xp: 850, currency: 800, loot: ['Harvester\'s Core'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m3',
    actNumber: 3,
    missionNumber: 23,
    name: 'Prophesied Devourer: Jungle Terror',
    description: 'Third Rift General. Jungle tribe terror. Shell armor. Ninja Turtles meets Zootopia aesthetic.',
    cinematicIntro: 'The jungle. The Devourer terrorizes tribes. Shell armor protects. Heroes must break through.',
    objectives: ['Break the shell armor', 'Defeat the Devourer', 'Save the tribes'],
    difficulty: 7,
    arena: 'jungle_temple',
    bossName: 'Prophesied Devourer',
    bossPhases: 3,
    storyBeat: 'Third Rift General falls. Tribes are saved. The jungle is free.',
    rewards: { xp: 800, currency: 750, loot: ['Devourer\'s Shell'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m4',
    actNumber: 3,
    missionNumber: 24,
    name: 'Silence Avatar: Tournament Saboteur',
    description: 'Fourth Rift General. Tournament saboteur. Memory-corrupted. The arena becomes a trap.',
    cinematicIntro: 'The arena. The Silence Avatar corrupts memories. Heroes must fight their own echoes.',
    objectives: ['Defeat memory echoes', 'Break the corruption', 'Defeat the Avatar'],
    difficulty: 8,
    arena: 'cross_point_arena',
    bossName: 'Silence Avatar',
    bossPhases: 3,
    storyBeat: 'Fourth Rift General falls. Memory corruption ends. The arena is cleansed.',
    rewards: { xp: 850, currency: 800, loot: ['Avatar\'s Mask'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m5',
    actNumber: 3,
    missionNumber: 25,
    name: 'Dark Seraphim: Corrupted Guardian',
    description: 'Fifth Rift General. Memory-corrupted guardian. Once a protector, now a destroyer. Tragic battle.',
    cinematicIntro: 'The Dark Seraphim. Once a guardian. Memory-corrupted. Heroes must free him—or defeat him.',
    objectives: ['Free the guardian', 'Break the corruption', 'Restore the Seraphim'],
    difficulty: 9,
    arena: 'divine_realm',
    bossName: 'Dark Seraphim',
    bossPhases: 4,
    storyBeat: 'Fifth Rift General falls. The guardian is freed. Tragedy becomes hope.',
    rewards: { xp: 900, currency: 850, loot: ['Seraphim\'s Wing'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m6',
    actNumber: 3,
    missionNumber: 26,
    name: 'The All High: Divine Trials',
    description: 'The Cosmic Judge. Five divine trials. Speed, magic, legend, unity, sacrifice. Prove worthiness.',
    cinematicIntro: 'The All High appears. Cosmic judge. Five trials await. Speed. Magic. Legend. Unity. Sacrifice.',
    objectives: ['Complete Trial 1: Speed', 'Complete Trial 2: Magic', 'Complete Trial 3: Legend', 'Complete Trial 4: Unity', 'Complete Trial 5: Sacrifice'],
    difficulty: 9,
    arena: 'divine_realm',
    bossName: 'The All High',
    bossPhases: 5,
    storyBeat: 'Divine trials. Heroes prove worthiness. The All High acknowledges their value.',
    rewards: { xp: 1000, currency: 1000, loot: ['Divine Acknowledgment'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m7',
    actNumber: 3,
    missionNumber: 27,
    name: 'Voidonus Imperion: The Void Emperor',
    description: 'The final boss. Four phases. Avatars → Silence Network → Throne Assault → Oblivion Core. Epic finale.',
    cinematicIntro: 'Voidonus Imperion. The Void Emperor. Betrayed guardian. Reality collapses around him. The final battle begins.',
    objectives: ['Phase 1: Defeat Avatars', 'Phase 2: Break Silence Network', 'Phase 3: Assault the Throne', 'Phase 4: Destroy Oblivion Core'],
    difficulty: 10,
    arena: 'ashen_expanse',
    bossName: 'Voidonus Imperion',
    bossPhases: 4,
    storyBeat: 'FINAL BOSS: Voidonus Imperion. Four phases. The ultimate battle. Reality hangs in the balance.',
    rewards: { xp: 2000, currency: 2000, loot: ['Void Emperor\'s Crown', 'Reality Stabilizer'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m8',
    actNumber: 3,
    missionNumber: 28,
    name: 'The Grand Star Wish',
    description: 'Seven Harmonarch Grand Stars. One wish. Restore all that was lost. The ultimate choice.',
    cinematicIntro: 'Seven Grand Stars align. One wish. Restore all that was lost. But at what cost?',
    objectives: ['Collect 7 Grand Stars', 'Make the wish', 'Face the consequences'],
    difficulty: 10,
    arena: 'divine_realm',
    storyBeat: 'The Grand Star Wish. Heroes restore all that was lost. But Kai-Jax must choose: fade or endure.',
    rewards: { xp: 1500, currency: 1500, loot: ['Grand Star', 'Wish Fragment'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act3_m9',
    actNumber: 3,
    missionNumber: 29,
    name: 'Kai-Jax: The Choice',
    description: 'Kai-Jax must choose. Fade away with restored heroes, or endure as the living symbol of hope.',
    cinematicIntro: 'The choice. Fade away with restored heroes. Or endure. Become the living symbol of hope. What will Kai-Jax choose?',
    objectives: ['Make the choice', 'Face the consequences', 'Accept your destiny'],
    difficulty: 9,
    arena: 'memory_nexus',
    requiredCharacters: ['kai-jax'],
    storyBeat: 'The choice. Kai-Jax decides. Fade or endure. The future is written.',
    rewards: { xp: 1200, currency: 1200, loot: ['Destiny Fragment'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act3_m10',
    actNumber: 3,
    missionNumber: 30,
    name: 'Epilogue: Unity\'s Dawn',
    description: 'The dawn breaks. Heroes restored. Reality saved. Kai-Jax endures. The legend continues.',
    cinematicIntro: 'The dawn breaks. Heroes restored. Reality saved. Kai-Jax endures. The legend continues. New adventures await.',
    objectives: ['Witness the epilogue', 'See the restored world', 'Begin new adventures'],
    difficulty: 1,
    arena: 'nexus_haven',
    storyBeat: 'EPILOGUE: The dawn breaks. Heroes restored. Reality saved. Kai-Jax endures. The legend continues.',
    rewards: { xp: 500, currency: 500, loot: ['Legend Badge', 'Epilogue Unlock'] },
    gameplayType: 'combat',
  },
];

export const ALL_STORY_MISSIONS: StoryMission[] = [
  ...ACT_I_STORY_MISSIONS,
  ...ACT_II_STORY_MISSIONS,
  ...ACT_III_STORY_MISSIONS,
];

export function getStoryMissionById(id: string): StoryMission | undefined {
  return ALL_STORY_MISSIONS.find((m) => m.id === id);
}

export function getStoryMissionsByAct(act: 1 | 2 | 3): StoryMission[] {
  if (act === 1) return ACT_I_STORY_MISSIONS;
  if (act === 2) return ACT_II_STORY_MISSIONS;
  return ACT_III_STORY_MISSIONS;
}

export function getStoryMissions(): StoryMission[] {
  return ALL_STORY_MISSIONS;
}
