/**
 * ULTIMATE ENTERTAINMENT ENTERPRISES PRESENTS
 * BEAST WARS STORY MODE
 * 30 Cinematic Missions — feral Beast Wars action, cinematic and playable
 * 
 * Experience the legendary story as you fight through the action!
 */

export interface StoryMission {
  id: string;
  actNumber: 1 | 2 | 3;
  missionNumber: number;
  name: string;
  description: string;
  cinematicIntro?: string;
  cinematicOutro?: string;
  objectives: string[];
  difficulty: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;
  bossName?: string;
  bossPhases?: number;
  arena: string;
  requiredCharacters?: string[];
  unlockableCharacters?: string[];
  storyBeat: string; // What happens in the story
  rewards: { xp: number; currency: number; loot: string[]; unlocks?: string[] };
  gameplayType: 'combat' | 'platforming' | 'stealth' | 'chase' | 'boss' | 'team' | 'survival';
}

// ============ ACT I: CONVERGENCE (Missions 1-10) ============
export const ACT_I_STORY_MISSIONS: StoryMission[] = [
  {
    id: 'story_act1_m1',
    actNumber: 1,
    missionNumber: 1,
    name: 'The Grand Tournament Begins',
    description: 'Radiant Jumper enters the Cross Point Arena. The crowd roars. But something feels wrong...',
    cinematicIntro: 'The arena lights blaze. Champions from across dimensions gather. Radiant Jumper steps into the spotlight.',
    objectives: ['Win your first match', 'Land 3 perfect dodges', 'Experience the arena atmosphere'],
    difficulty: 1,
    arena: 'cross_point_arena',
    requiredCharacters: ['radiant-jumper'],
    storyBeat: 'Radiant Jumper debuts. The tournament begins with high energy, but strange glitches appear.',
    rewards: { xp: 200, currency: 150, loot: ['Arena Badge'], unlocks: ['kaison'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act1_m2',
    actNumber: 1,
    missionNumber: 2,
    name: 'Kaison: The Swift Guardian Arrives',
    description: 'Kaison enters the tournament. His fox-wolf hybrid form moves with precision. But his past haunts him.',
    cinematicIntro: 'Kaison arrives, tactical jacket flowing. He remembers his lost mentor. The tournament is his chance to prove himself.',
    objectives: ['Master Fox Dash', 'Use web control 3 times', 'Win without taking damage'],
    difficulty: 2,
    arena: 'cross_point_arena',
    requiredCharacters: ['kaison'],
    storyBeat: 'Kaison debuts. His tactical skills shine, but survivor\'s guilt weighs heavy.',
    rewards: { xp: 250, currency: 200, loot: ['Tactical Crest'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act1_m3',
    actNumber: 1,
    missionNumber: 3,
    name: 'The Broken Bracket',
    description: 'The tournament bracket glitches. Reality tears. Void creatures pour through. This is no longer a game.',
    cinematicIntro: 'The screen flickers. The bracket shatters. A Rift tears open. Void beasts emerge. The tournament becomes a battlefield.',
    objectives: ['Defeat 5 Void Grunts', 'Close the Rift', 'Survive the chaos'],
    difficulty: 3,
    arena: 'cross_point_arena',
    bossName: 'Rift Warden',
    bossPhases: 2,
    storyBeat: 'INCITING INCIDENT: The tournament is invaded. Reality is under attack. Heroes must unite.',
    rewards: { xp: 300, currency: 250, loot: ['Rift Fragment'], unlocks: ['jaxon'] },
    gameplayType: 'survival',
  },
  {
    id: 'story_act1_m4',
    actNumber: 1,
    missionNumber: 4,
    name: 'Jaxon: Speed of Chaos',
    description: 'Jaxon bursts onto the scene. His electric quills crackle. Speed solves everything—or so he thinks.',
    cinematicIntro: 'Jaxon arrives in a blur. His isolation breaks. For the first time, he\'s not alone—he\'s needed.',
    objectives: ['Chain 5 speed attacks', 'Use Spin Dash 3 times', 'Win with style'],
    difficulty: 2,
    arena: 'emerald_frontier',
    requiredCharacters: ['jaxon'],
    storyBeat: 'Jaxon debuts. His speed is unmatched, but he learns speed alone isn\'t enough.',
    rewards: { xp: 250, currency: 200, loot: ['Speed Gem'] },
    gameplayType: 'chase',
  },
  {
    id: 'story_act1_m5',
    actNumber: 1,
    missionNumber: 5,
    name: 'City Under Siege',
    description: 'The Bronx streets become a warzone. Beast-hybrids fight side-by-side. Zootopia meets Marvel Ultimate Alliance.',
    cinematicIntro: 'The city erupts. Civilians flee. Beast-hybrids emerge from alleys. Heroes and citizens unite.',
    objectives: ['Protect 10 civilians', 'Defeat 8 Void Grunts', 'Clear the district'],
    difficulty: 4,
    arena: 'bronx_streets',
    storyBeat: 'City defense begins. Heroes realize the scope of the invasion. Unity is essential.',
    rewards: { xp: 350, currency: 300, loot: ['City Defender Badge'] },
    gameplayType: 'team',
  },
  {
    id: 'story_act1_m6',
    actNumber: 1,
    missionNumber: 6,
    name: 'Kaison vs Jaxon: Rivalry Ignited',
    description: 'Two legends clash. Kaison\'s tactics vs Jaxon\'s speed. But they must learn to work together.',
    cinematicIntro: 'They meet in the arena. Different styles. Different wounds. But the same goal: protect the innocent.',
    objectives: ['Fight to a draw', 'Learn each other\'s moves', 'Form a temporary alliance'],
    difficulty: 3,
    arena: 'cross_point_arena',
    requiredCharacters: ['kaison', 'jaxon'],
    storyBeat: 'Kaison and Jaxon clash, then unite. Their rivalry becomes respect. The foundation for fusion begins.',
    rewards: { xp: 300, currency: 250, loot: ['Rivalry Crest'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act1_m7',
    actNumber: 1,
    missionNumber: 7,
    name: 'Silver: The Time Fixer',
    description: 'Silver arrives. Time itself bends. He sees the death loops. He must prevent catastrophe.',
    cinematicIntro: 'Time freezes. Silver steps through. He sees Radiant Jumper\'s death loop. He must intervene.',
    objectives: ['Use time manipulation', 'Prevent a death loop', 'Stabilize the timeline'],
    difficulty: 4,
    arena: 'memory_nexus',
    requiredCharacters: ['silver'],
    unlockableCharacters: ['silver'],
    storyBeat: 'Silver reveals the timeline is fracturing. Death loops threaten reality. He becomes a mentor.',
    rewards: { xp: 400, currency: 350, loot: ['Time Shard'], unlocks: ['silver'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act1_m8',
    actNumber: 1,
    missionNumber: 8,
    name: 'The Emerald Frontier Chase',
    description: 'Speed trials on momentum lanes. Loop-de-loops. A chase through impossible geometry. Beast-kin parkour at impossible speed.',
    cinematicIntro: 'The Emerald Frontier opens. Momentum lanes twist through reality. A high-speed chase begins.',
    objectives: ['Complete the speed trial', 'Hit all momentum lanes', 'Catch the Void Runner'],
    difficulty: 5,
    arena: 'emerald_frontier',
    storyBeat: 'Speed trial reveals the heroes\' potential. Momentum becomes a weapon. The chase is on.',
    rewards: { xp: 450, currency: 400, loot: ['Momentum Ring'] },
    gameplayType: 'chase',
  },
  {
    id: 'story_act1_m9',
    actNumber: 1,
    missionNumber: 9,
    name: 'Lunara: The Harmony Anchor',
    description: 'Lunara appears. Her healing resonance soothes. She hears unborn Kai-Jax crying in the Weave.',
    cinematicIntro: 'Harmony pulses through the battlefield. Lunara arrives. She senses something new—something powerful—being born.',
    objectives: ['Heal 3 allies', 'Use Harmony Resonance', 'Protect Lunara'],
    difficulty: 3,
    arena: 'memory_nexus',
    requiredCharacters: ['lunara'],
    unlockableCharacters: ['lunara'],
    storyBeat: 'Lunara joins. She senses Kai-Jax before he exists. The Triad begins to form.',
    rewards: { xp: 350, currency: 300, loot: ['Harmony Gem'], unlocks: ['lunara'] },
    gameplayType: 'team',
  },
  {
    id: 'story_act1_m10',
    actNumber: 1,
    missionNumber: 10,
    name: 'First Kai-Jax Echo',
    description: 'A memory echo appears. Three tails. Gold, blue, white. Kai-Jax exists in the future—and the past.',
    cinematicIntro: 'The Weave shimmers. An echo forms. Three tails materialize. Gold, blue, white. The Memory King appears—briefly.',
    objectives: ['Witness the echo', 'Learn from the future', 'Prepare for fusion'],
    difficulty: 6,
    arena: 'memory_nexus',
    bossName: 'Echo Guardian',
    bossPhases: 1,
    storyBeat: 'MIDPOINT: Kai-Jax echo appears. The future is written. Heroes must make it happen.',
    rewards: { xp: 500, currency: 450, loot: ['Echo Fragment'], unlocks: ['kai-jax'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act1_m11',
    actNumber: 1,
    missionNumber: 11,
    name: 'The Void Bloom',
    description: 'A massive Rift opens in the park. Void flowers drain the color from the world. Stop the decay.',
    objectives: ['Destroy 5 Void Blooms', 'Defeat the corrupted park ranger', 'Restore the color'],
    difficulty: 4,
    arena: 'green-valley',
    storyBeat: 'The invasion turns environmental. The world literal loses its saturation as the Void feeds.',
    rewards: { xp: 400, currency: 350, loot: ['Chroma Seed'] },
    gameplayType: 'platforming',
  },
  {
    id: 'story_act1_m12',
    actNumber: 1,
    missionNumber: 12,
    name: 'Glitch Syndicate Infiltration',
    description: 'A local gang has started using Void tech. Infiltrate their hideout and find out who supplied them.',
    objectives: ['Sneak past the guards', 'Hack the mainframe', 'Defeat Syndicate Leader Vex'],
    difficulty: 5,
    arena: 'bronx_streets',
    bossName: 'Syndicate Vex',
    storyBeat: 'Human-Beast gangs are being manipulated by the Void. The conspiracy deepens.',
    rewards: { xp: 450, currency: 400, loot: ['Encrypted Data-Pad'] },
    gameplayType: 'stealth',
  },
  {
    id: 'story_act1_m13',
    actNumber: 1,
    missionNumber: 13,
    name: 'Momentum Mastery',
    description: 'The Void Runner returns. Jaxon must prove his speed on the high-altitude momentum rails.',
    objectives: ['Win the race', 'Avoid the electrified barriers', 'Perform a 20-hit combo on the move'],
    difficulty: 5,
    arena: 'emerald_frontier',
    requiredCharacters: ['jaxon'],
    storyBeat: 'Jaxon learns that speed isn\'t just about moving fast—it\'s about moving with purpose.',
    rewards: { xp: 400, currency: 400, loot: ['Kinetic Glove'] },
    gameplayType: 'chase',
  },
  {
    id: 'story_act1_m14',
    actNumber: 1,
    missionNumber: 14,
    name: 'The Whispering Shadows',
    description: 'Shadowy figures appear in the alleyways. They don\'t attack—they haunt. Kaison must solve the riddle.',
    objectives: ['Collect 3 Memory Whispers', 'survive the shadow ambush', 'Uncover the mentor\'s secret'],
    difficulty: 6,
    arena: 'bronx_streets',
    requiredCharacters: ['kaison'],
    storyBeat: 'Kaison confronts a memory of his mentor. Is the Void using his grief against him?',
    rewards: { xp: 500, currency: 450, loot: ['Mentor\'s Scarf'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act1_m15',
    actNumber: 1,
    missionNumber: 15,
    name: 'Lava Fortress Siege',
    description: 'The first major stronghold of the Void. A hot-headed challenge. Heroes must stay cool.',
    objectives: ['Cross the lava bridges', 'Disable the thermal pumps', 'Defeat Magma Crawler'],
    difficulty: 6,
    arena: 'lava-fortress',
    bossName: 'Magma Crawler',
    storyBeat: 'The heroes assault their first Void base. They find evidence of an Emperor behind the Rift.',
    rewards: { xp: 600, currency: 500, loot: ['Fireproof Hide'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act1_m16',
    actNumber: 1,
    missionNumber: 16,
    name: 'Lunara\'s Song',
    description: 'The void silence is deafening. Lunara must sing the Song of Harmony to stabilize the district.',
    objectives: ['Defend Lunara for 3 minutes', 'Maintain the Harmony Meter', 'Repel the Void Wraiths'],
    difficulty: 5,
    arena: 'memory_nexus',
    requiredCharacters: ['lunara'],
    storyBeat: 'Lunara\'s importance as the team\'s anchor is solidified. Without her, the heroes would lose themselves.',
    rewards: { xp: 550, currency: 500, loot: ['Resonance Stone'] },
    gameplayType: 'survival',
  },
  {
    id: 'story_act1_m17',
    actNumber: 1,
    missionNumber: 17,
    name: 'The Glitch Storm',
    description: 'Reality is literally breaking. Geometry is shifting. Reach the eye of the storm.',
    objectives: ['Survive the shifting terrain', 'Avoid the glitch spikes', 'Reach the stability pylon'],
    difficulty: 7,
    arena: 'space-station',
    storyBeat: 'The world is becoming unrecognizable. The heroes are running out of time.',
    rewards: { xp: 650, currency: 600, loot: ['Stability Core'] },
    gameplayType: 'platforming',
  },
  {
    id: 'story_act1_m18',
    actNumber: 1,
    missionNumber: 18,
    name: 'Duel of the Century',
    description: 'The Void Tournament Final. Radiant Jumper vs the Void Champion. The world is watching.',
    objectives: ['Win the match', 'Finish with an Ultimate', 'Save the Cross Point Arena'],
    difficulty: 8,
    arena: 'cross_point_arena',
    bossName: 'Void Champion Zerox',
    storyBeat: 'The tournament ends in chaos. Book 1 Climax. The heroes realize the tournament was a trap to harvest their synergy.',
    rewards: { xp: 1000, currency: 1000, loot: ['Grand Final Medal'] },
    gameplayType: 'boss',
  },
];

// ============ ACT II: FRACTURED LIGHT (Missions 19-36) ============
export const ACT_II_STORY_MISSIONS: StoryMission[] = [
  {
    id: 'story_act2_m1',
    actNumber: 2,
    missionNumber: 19,
    name: 'Six Months Later: Scattered',
    description: 'The heroes are scattered. Hunted. Desperate. The Void has won ground. Hope is fading.',
    cinematicIntro: 'Six months pass. The heroes are on the run. Safe zones shrink. The Void spreads. But they fight on.',
    objectives: ['Survive the ambush', 'Regroup with allies', 'Find a safe zone'],
    difficulty: 5,
    arena: 'bronx_streets',
    storyBeat: 'Time jump. Heroes are scattered. The war has escalated. Unity is harder than ever.',
    rewards: { xp: 400, currency: 350, loot: ['Survivor Badge'] },
    gameplayType: 'survival',
  },
  {
    id: 'story_act2_m2',
    actNumber: 2,
    missionNumber: 20,
    name: 'The Last Stand Defense',
    description: 'One final stronghold. Heroes make their stand. Batman-style tactical defense meets Marvel team-up.',
    cinematicIntro: 'The last safe zone. Void forces mass. Heroes prepare. This is it—win or lose everything.',
    objectives: ['Defend for 5 minutes', 'Protect the stronghold', 'Hold the line'],
    difficulty: 7,
    arena: 'nexus_haven',
    storyBeat: 'ROCK BOTTOM: Last stand. Heroes pushed to the limit. Desperation breeds innovation.',
    rewards: { xp: 600, currency: 500, loot: ['Last Stand Medal'] },
    gameplayType: 'survival',
  },
  {
    id: 'story_act2_m3',
    actNumber: 2,
    missionNumber: 21,
    name: 'Cobalt Blur: Speed Legend',
    description: 'Cobalt Blur arrives. The speed legend. He trains Kaison and Jaxon. Speed becomes art.',
    cinematicIntro: 'A blur. Cobalt Blur appears. He\'s seen it all. Now he teaches the next generation.',
    objectives: ['Learn Chaos Control', 'Master speed techniques', 'Prove your worth'],
    difficulty: 4,
    arena: 'emerald_frontier',
    requiredCharacters: ['cobalt-blur'],
    unlockableCharacters: ['cobalt-blur'],
    storyBeat: 'Cobalt Blur mentors. Speed becomes more than movement—it becomes control.',
    rewards: { xp: 450, currency: 400, loot: ['Speed Master Badge'], unlocks: ['cobalt-blur'] },
    gameplayType: 'chase',
  },
  {
    id: 'story_act2_m4',
    actNumber: 2,
    missionNumber: 22,
    name: 'The Skyforge Climb',
    description: 'Vertical challenge. Climbable towers. Storm clouds. Ninja Turtles-style platforming meets Batman traversal.',
    cinematicIntro: 'The Skyforge rises. Towers pierce storm clouds. Heroes must climb. The Void waits above.',
    objectives: ['Climb to the summit', 'Avoid storm strikes', 'Reach the peak'],
    difficulty: 6,
    arena: 'skyforge_plateau',
    storyBeat: 'Vertical challenge. Heroes prove their determination. The climb is the test.',
    rewards: { xp: 500, currency: 450, loot: ['Skyforge Crest'] },
    gameplayType: 'platforming',
  },
  {
    id: 'story_act2_m5',
    actNumber: 2,
    missionNumber: 23,
    name: 'The First Fusion: Kai-Jax Born',
    description: 'Kaison and Jaxon fuse. Three tails emerge. Gold, blue, white. Kai‑Jax is born. The Memory King awakens.',
    cinematicIntro: 'They stand together. Synergy meter fills. 100%. The fusion begins. Three tails emerge. Kai-Jax is born.',
    objectives: ['Achieve 100% synergy', 'Fuse into Kai-Jax', 'Master the three tails'],
    difficulty: 8,
    arena: 'memory_nexus',
    requiredCharacters: ['kaison', 'jaxon'],
    storyBeat: 'MIDPOINT: First fusion. Kai‑Jax is born. The Memory King awakens. Everything changes.',
    rewards: { xp: 800, currency: 700, loot: ['Fusion Core'], unlocks: ['kai-jax'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act2_m6',
    actNumber: 2,
    missionNumber: 24,
    name: 'Kai-Jax: Memory Echo Dive',
    description: 'Kai-Jax dives into memories. Past battles replay. He learns from fallen heroes. Memory is power.',
    cinematicIntro: 'Kai-Jax closes his eyes. The Weave opens. Memories flood in. Past battles. Fallen heroes. He learns.',
    objectives: ['Dive into 3 memories', 'Learn from echoes', 'Master Memory Dive'],
    difficulty: 5,
    arena: 'memory_nexus',
    requiredCharacters: ['kai-jax'],
    storyBeat: 'Kai-Jax masters memory magic. He can relive the past. Learn from the fallen.',
    rewards: { xp: 550, currency: 500, loot: ['Memory Shard'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act2_m7',
    actNumber: 2,
    missionNumber: 25,
    name: 'Prison Break: Free the Captured',
    description: 'Void prison. Heroes captured. Stealth mission. Batman-style infiltration meets Ninja Turtles teamwork.',
    cinematicIntro: 'The Void prison looms. Heroes are inside. Time for a rescue. Stealth and teamwork required.',
    objectives: ['Infiltrate the prison', 'Free 5 captured heroes', 'Escape without detection'],
    difficulty: 6,
    arena: 'rift_citadel',
    storyBeat: 'Prison break. Heroes rescue allies. The team grows. Unity strengthens.',
    rewards: { xp: 600, currency: 550, loot: ['Liberator Badge'] },
    gameplayType: 'stealth',
  },
  {
    id: 'story_act2_m8',
    actNumber: 2,
    missionNumber: 26,
    name: 'The Rift Generals: Void Tower Warden',
    description: 'First Rift General. Shield-based fortress. Tactical battle. Marvel Ultimate Alliance boss fight.',
    cinematicIntro: 'The Void Tower rises. The Warden guards it. Shield-based defense. Heroes must break through.',
    objectives: ['Break the shield', 'Defeat the Warden', 'Claim the tower'],
    difficulty: 7,
    arena: 'void_tower',
    bossName: 'Void Tower Warden',
    bossPhases: 3,
    storyBeat: 'First Rift General falls. Progress. The Void weakens. Hope returns.',
    rewards: { xp: 700, currency: 600, loot: ['Warden\'s Shield'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act2_m9',
    actNumber: 2,
    missionNumber: 27,
    name: 'Team Unified: The Triad Forms',
    description: 'Silver, Lunara, and Kai-Jax unite. The Triad forms. Harmony, Time, and Memory combine.',
    cinematicIntro: 'Three stand together. Silver (Time). Lunara (Harmony). Kai-Jax (Memory). The Triad forms.',
    objectives: ['Form the Triad', 'Use combined powers', 'Stabilize a Rift'],
    difficulty: 6,
    arena: 'memory_nexus',
    requiredCharacters: ['silver', 'lunara', 'kai-jax'],
    storyBeat: 'The Triad forms. Three powers unite. Reality stabilizes. The team is complete.',
    rewards: { xp: 650, currency: 600, loot: ['Triad Crest'] },
    gameplayType: 'team',
  },
  {
    id: 'story_act2_m10',
    actNumber: 2,
    missionNumber: 28,
    name: 'District Zero Reconstruction',
    description: 'Rebuild the memory nexus. The blueprint of the old world is the only way to save the new one.',
    objectives: ['Collect 5 Blueprint Shards', 'Protect the reconstruction drone', 'Defeat the Glitch Scavengers'],
    difficulty: 6,
    arena: 'memory_nexus',
    storyBeat: 'The heroes begin to rebuild. Memory is literally used to restore the broken city geometry.',
    rewards: { xp: 500, currency: 450, loot: ['City Blueprint'] },
    gameplayType: 'team',
  },
  {
    id: 'story_act2_m11',
    actNumber: 2,
    missionNumber: 29,
    name: 'The Neon Shadows',
    description: 'A chase through the neon-soaked lower districts. Speed Kin vs Void Cycle-Riders.',
    objectives: ['Don\'t drop below 200mph', 'Takedown 10 riders', 'Escape the EMP pulse'],
    difficulty: 7,
    arena: 'emerald_frontier',
    storyBeat: 'The heroes use the city\'s neon grid to hyper-charge their speed. Jaxon feels at home.',
    rewards: { xp: 550, currency: 500, loot: ['Neon Spark'] },
    gameplayType: 'chase',
  },
  {
    id: 'story_act2_m12',
    actNumber: 2,
    missionNumber: 30,
    name: 'Shadow of the Mentor',
    description: 'The Void creates a perfect clone of Kaison\'s mentor. Can Kaison fight his own hope?',
    objectives: ['Win the psychological duel', 'Break the mental loop', 'Defeat Echo-Mentor'],
    difficulty: 8,
    arena: 'memory_nexus',
    requiredCharacters: ['kaison'],
    storyBeat: 'Kaison finally lets go of the past. He realize he isn\'t just a student anymore—he is a legend.',
    rewards: { xp: 800, currency: 600, loot: ['Shattered Legacy'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act2_m13',
    actNumber: 2,
    missionNumber: 31,
    name: 'Rift Mining Colony',
    description: 'The Void is mining the planet\'s core for Memory Ore. Shut it down.',
    objectives: ['Sabotage 3 drills', 'Evacuate the miners', 'Defeat the Mining Overseer'],
    difficulty: 7,
    arena: 'lava-fortress',
    storyBeat: 'The Void\'s plan is revealed: they aren\'t just invading, they are harvesting the planet\'s history.',
    rewards: { xp: 600, currency: 550, loot: ['Memory Ore'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act2_m14',
    actNumber: 2,
    missionNumber: 32,
    name: 'Hyper-Speed Tunnel',
    description: 'The Tunnel between districts is a gauntlet. Chaos Control is the only way through.',
    objectives: ['Survive the tunnel warp', 'Use Chaos Control 5 times', 'Reach the other side'],
    difficulty: 8,
    arena: 'space-station',
    requiredCharacters: ['cobalt-blur'],
    storyBeat: 'The heroes learn to travel between dimensions using their own speed.',
    rewards: { xp: 700, currency: 650, loot: ['Warp Drive'] },
    gameplayType: 'platforming',
  },
  {
    id: 'story_act2_m15',
    actNumber: 2,
    missionNumber: 33,
    name: 'The Council of Beasts',
    description: 'The ancient beast leaders aren\'t sure about Kai-Jax. Prove your worth in the trial of the elders.',
    objectives: ['Defeat the Elder Spirits', 'Show wisdom in combat', 'Earn the Legend title'],
    difficulty: 9,
    arena: 'jungle_temple',
    storyBeat: 'Kai-Jax is officially recognized as the Memory King by the ancients.',
    rewards: { xp: 900, currency: 800, loot: ['Elder\'s Amulet'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act2_m16',
    actNumber: 2,
    missionNumber: 34,
    name: 'The Great Glitch Storm: Peak',
    description: 'The storm has reached its peak. The Citadel is visible. One final climb.',
    objectives: ['Scale the vertical rift', 'Avoid falling debris', 'Open the Citadel Gate'],
    difficulty: 8,
    arena: 'skyforge_plateau',
    storyBeat: 'The Final Goal is in sight. The march on the Emperor begins.',
    rewards: { xp: 750, currency: 700, loot: ['Storm Breaker'] },
    gameplayType: 'platforming',
  },
  {
    id: 'story_act2_m17',
    actNumber: 2,
    missionNumber: 35,
    name: 'Malakor\'s Betrayal',
    description: 'Malakor was supposed to be an ally. He wants the Memory Ore for himself.',
    objectives: ['Defeat Malakor', 'Protect the ore reserves', 'Learn Malakor\'s true motive'],
    difficulty: 9,
    arena: 'lava-fortress',
    bossName: 'Malakor the Greedy',
    storyBeat: 'Sub-Plot Climax. A trusted ally falls to greed, showing that the Void corrupts not just space, but hearts.',
    rewards: { xp: 1000, currency: 900, loot: ['Betrayer\'s Fang'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act2_m18',
    actNumber: 2,
    missionNumber: 36,
    name: 'Unity\'s Dawn: The Gathering',
    description: 'The team gather at the foot of the Rift Citadel. Every hero we saved is here.',
    objectives: ['Recruit the 5 saved factions', 'Plan the final assault', 'Prepare for the Emperor'],
    difficulty: 7,
    arena: 'nexus_haven',
    storyBeat: 'ACT II FINALE. The army is ready. The legend of Kai-Jax has inspired the world. We go to war.',
    rewards: { xp: 1200, currency: 1000, loot: ['Unity War Banner'] },
    gameplayType: 'team',
  },
];

// ============ ACT III: UNITY'S DAWN (Missions 37-54) ============
export const ACT_III_STORY_MISSIONS: StoryMission[] = [
  {
    id: 'story_act3_m1',
    actNumber: 3,
    missionNumber: 37,
    name: 'The Rift Citadel Siege',
    description: 'The mobile fortress. Multi-stage siege. Marvel Ultimate Alliance scale. Heroes assault the Citadel.',
    cinematicIntro: 'The Rift Citadel looms. Mobile fortress. Multi-stage siege. Heroes charge. The final battle begins.',
    objectives: ['Breach the outer wall', 'Fight through 3 stages', 'Reach the inner sanctum'],
    difficulty: 8,
    arena: 'rift_citadel',
    storyBeat: 'The siege begins. Heroes assault the Citadel. Stage by stage, they advance.',
    rewards: { xp: 800, currency: 750, loot: ['Siege Badge'] },
    gameplayType: 'team',
  },
  {
    id: 'story_act3_m2',
    actNumber: 3,
    missionNumber: 38,
    name: 'Rift Harvester: Archipelago Terror',
    description: 'Second Rift General. Life-draining archipelago. Zootopia-style environment. Epic boss battle.',
    cinematicIntro: 'The archipelago. The Harvester drains life. Heroes must fight on water, land, and air.',
    objectives: ['Survive the life drain', 'Defeat the Harvester', 'Restore the archipelago'],
    difficulty: 8,
    arena: 'archipelago',
    bossName: 'Rift Harvester',
    bossPhases: 4,
    storyBeat: 'Second Rift General falls. The archipelago is saved. Heroes advance.',
    rewards: { xp: 850, currency: 800, loot: ['Harvester\'s Core'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m3',
    actNumber: 3,
    missionNumber: 39,
    name: 'Prophesied Devourer: Jungle Terror',
    description: 'Third Rift General. Jungle tribe terror. Shell armor. Ninja Turtles meets Zootopia aesthetic.',
    cinematicIntro: 'The jungle. The Devourer terrorizes tribes. Shell armor protects. Heroes must break through.',
    objectives: ['Break the shell armor', 'Defeat the Devourer', 'Save the tribes'],
    difficulty: 7,
    arena: 'jungle_temple',
    bossName: 'Prophesied Devourer',
    bossPhases: 3,
    storyBeat: 'Third Rift General falls. Tribes are saved. The jungle is free.',
    rewards: { xp: 800, currency: 750, loot: ['Devourer\'s Shell'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m4',
    actNumber: 3,
    missionNumber: 40,
    name: 'Silence Avatar: Tournament Saboteur',
    description: 'Fourth Rift General. Tournament saboteur. Memory-corrupted. The arena becomes a trap.',
    cinematicIntro: 'The arena. The Silence Avatar corrupts memories. Heroes must fight their own echoes.',
    objectives: ['Defeat memory echoes', 'Break the corruption', 'Defeat the Avatar'],
    difficulty: 8,
    arena: 'cross_point_arena',
    bossName: 'Silence Avatar',
    bossPhases: 3,
    storyBeat: 'Fourth Rift General falls. Memory corruption ends. The arena is cleansed.',
    rewards: { xp: 850, currency: 800, loot: ['Avatar\'s Mask'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m5',
    actNumber: 3,
    missionNumber: 41,
    name: 'Dark Seraphim: Corrupted Guardian',
    description: 'Fifth Rift General. Memory-corrupted guardian. Once a protector, now a destroyer. Tragic battle.',
    cinematicIntro: 'The Dark Seraphim. Once a guardian. Memory-corrupted. Heroes must free him—or defeat him.',
    objectives: ['Free the guardian', 'Break the corruption', 'Restore the Seraphim'],
    difficulty: 9,
    arena: 'divine_realm',
    bossName: 'Dark Seraphim',
    bossPhases: 4,
    storyBeat: 'Fifth Rift General falls. The guardian is freed. Tragedy becomes hope.',
    rewards: { xp: 900, currency: 850, loot: ['Seraphim\'s Wing'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m6',
    actNumber: 3,
    missionNumber: 42,
    name: 'The All High: Divine Trials',
    description: 'The Cosmic Judge. Five divine trials. Speed, magic, legend, unity, sacrifice. Prove worthiness.',
    cinematicIntro: 'The All High appears. Cosmic judge. Five trials await. Speed. Magic. Legend. Unity. Sacrifice.',
    objectives: ['Complete Trial 1: Speed', 'Complete Trial 2: Magic', 'Complete Trial 3: Legend', 'Complete Trial 4: Unity', 'Complete Trial 5: Sacrifice'],
    difficulty: 9,
    arena: 'divine_realm',
    bossName: 'The All High',
    bossPhases: 5,
    storyBeat: 'Divine trials. Heroes prove worthiness. The All High acknowledges their value.',
    rewards: { xp: 1000, currency: 1000, loot: ['Divine Acknowledgment'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m7',
    actNumber: 3,
    missionNumber: 43,
    name: 'Void Horizon Raid',
    description: 'Assault the edge of the universe. The Void is consuming the stars.',
    objectives: ['Destroy 10 Void Pylons', 'Win the space duel', 'Close the Mega-Rift'],
    difficulty: 9,
    arena: 'space-station',
    storyBeat: 'The war reaches the cosmos. The heroes fight to save the very stars themselves.',
    rewards: { xp: 1200, currency: 1000, loot: ['Starlight Fragment'] },
    gameplayType: 'combat',
  },
  {
    id: 'story_act3_m8',
    actNumber: 3,
    missionNumber: 44,
    name: 'The Memory King\'s Ascent',
    description: 'Kai-Jax must climb the Memory Spire to reclaim the planet\'s history.',
    objectives: ['Climb the shifting Spire', 'Defeat the Spire Guardians', 'Unlock the History Core'],
    difficulty: 8,
    arena: 'memory_nexus',
    requiredCharacters: ['kai-jax'],
    storyBeat: 'Kai-Jax finally understands his true power: he doesn\'t just remember history, he can re-write it.',
    rewards: { xp: 1100, currency: 1000, loot: ['History Key'] },
    gameplayType: 'platforming',
  },
  {
    id: 'story_act3_m9',
    actNumber: 3,
    missionNumber: 45,
    name: 'Echoes of the Void',
    description: 'The Emperor sends his most powerful clones. They are the heroes\' own dark reflections.',
    objectives: ['Defeat Dark Kai-Jax', 'Defeat Dark Cobalt Blur', 'Win the mirror match'],
    difficulty: 10,
    arena: 'ashen_expanse',
    storyBeat: 'The final test of ego. To defeat the Void, the heroes must first defeat the worst parts of themselves.',
    rewards: { xp: 1500, currency: 1200, loot: ['Reflective Plate'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m10',
    actNumber: 3,
    missionNumber: 46,
    name: 'The Last Stand: World Heart',
    description: 'The Void Emperor has reached the world heart. Stop him before he deletes everything.',
    objectives: ['Defend the heart for 5 minutes', 'Repel 100 enemies', 'Don\'t let health drop below 50%'],
    difficulty: 9,
    arena: 'nexus_haven',
    storyBeat: 'The final defensive battle. All factions unite for one last, desperate stand.',
    rewards: { xp: 1300, currency: 1100, loot: ['World Heart Fragment'] },
    gameplayType: 'survival',
  },
  {
    id: 'story_act3_m11',
    actNumber: 3,
    missionNumber: 47,
    name: 'Lava Fortress: Core Melt',
    description: 'The lava fortress is exploding. Escape before the planet breaks.',
    objectives: ['Escape the fortress', 'Rescue 5 trapped workers', 'Avoid the magma floods'],
    difficulty: 8,
    arena: 'lava-fortress',
    storyBeat: 'The world is literally falling apart. The stakes couldn\'t be higher.',
    rewards: { xp: 900, currency: 800, loot: ['Magma Shard'] },
    gameplayType: 'platforming',
  },
  {
    id: 'story_act3_m12',
    actNumber: 3,
    missionNumber: 48,
    name: 'The Rainbow Bridge Charge',
    description: 'Charging across the Rainbow Bridge to reach the Divine Realm.',
    objectives: ['Takedown 20 Void Knights', 'Keep the combo above 10', 'Reach the Gate'],
    difficulty: 8,
    arena: 'rainbow-castle',
    storyBeat: 'A glorious charge. The music swells as the heroes ride toward their destiny.',
    rewards: { xp: 1000, currency: 900, loot: ['Rainbow Scale'] },
    gameplayType: 'chase',
  },
  {
    id: 'story_act3_m13',
    actNumber: 3,
    missionNumber: 49,
    name: 'Divine Trial: Unity',
    description: 'One final trial from the All High. The team must act as one.',
    objectives: ['Win without anyone falling', 'Use 3 Team Ultimates', 'Defeat the Divine Mirror'],
    difficulty: 9,
    arena: 'divine_realm',
    storyBeat: 'The All High is impressed. The heroes have proven that unity is the ultimate power.',
    rewards: { xp: 1200, currency: 1100, loot: ['Mark of Unity'] },
    gameplayType: 'team',
  },
  {
    id: 'story_act3_m14',
    actNumber: 3,
    missionNumber: 50,
    name: 'The Void Spire: Infiltration',
    description: 'We are inside. The Emperor is at the top.',
    objectives: ['Sneak past the guards', 'Disable the security network', 'Reach the Throne Room'],
    difficulty: 8,
    arena: 'void_tower',
    storyBeat: 'The final stealth mission. The tension is at its peak. No turning back.',
    rewards: { xp: 1000, currency: 900, loot: ['Stealth Boots'] },
    gameplayType: 'stealth',
  },
  {
    id: 'story_act3_m15',
    actNumber: 3,
    missionNumber: 51,
    name: 'Voidonus Imperion: Phase 1',
    description: 'The battle begins. Avatars and the Silence Network.',
    objectives: ['Defeat the 4 Avatars', 'Break the Silence Network', 'Survive the throne pulse'],
    difficulty: 10,
    arena: 'ashen_expanse',
    bossName: 'Voidonus Imperion',
    storyBeat: 'The final battle begins. The Emperor\'s power is overwhelming.',
    rewards: { xp: 1500, currency: 1500, loot: ['Emperor\'s Shard'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m16',
    actNumber: 3,
    missionNumber: 52,
    name: 'Voidonus Imperion: The Throne Assault',
    description: 'assaulting the throne. Reality is flickering.',
    objectives: ['Break the Emperor\'s shield', 'Survive the reality shifts', 'Reach Phase 3'],
    difficulty: 10,
    arena: 'ashen_expanse',
    bossName: 'Voidonus Imperion',
    storyBeat: 'The Emperor is desperate. He begins deleting random parts of the arena geometry.',
    rewards: { xp: 2000, currency: 2000, loot: ['Throne Fragment'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m17',
    actNumber: 3,
    missionNumber: 53,
    name: 'Voidonus Imperion: Oblivion Core',
    description: 'The final core. The end of everything—or a new beginning.',
    objectives: ['Destroy the Oblivion Core', 'Win the final duel', 'Save reality'],
    difficulty: 10,
    arena: 'ashen_expanse',
    bossName: 'Voidonus Imperion',
    storyBeat: 'GRAND FINALE. The Emperor is defeated. Reality is saved. The Void collapses.',
    rewards: { xp: 5000, currency: 5000, loot: ['The Memory King\'s Crown'] },
    gameplayType: 'boss',
  },
  {
    id: 'story_act3_m18',
    actNumber: 3,
    missionNumber: 54,
    name: 'Epilogue: Unity\'s Dawn',
    description: 'The dawn breaks. Heroes restored. Reality saved. Kai-Jax endures. The legend continues.',
    cinematicIntro: 'The dawn breaks. Heroes restored. Reality saved. Kai-Jax endures. The legend continues. New adventures await.',
    objectives: ['Witness the epilogue', 'See the restored world', 'Begin new adventures'],
    difficulty: 1,
    arena: 'nexus_haven',
    storyBeat: 'EPILOGUE: All 54 chapters complete. The saga is written. New horizons await.',
    rewards: { xp: 1000, currency: 1000, loot: ['Completion Medal', 'New Game+ Unlock'] },
    gameplayType: 'combat',
  },
];

export const ALL_STORY_MISSIONS: StoryMission[] = [
  ...ACT_I_STORY_MISSIONS,
  ...ACT_II_STORY_MISSIONS,
  ...ACT_III_STORY_MISSIONS,
];

export function getStoryMissionById(id: string): StoryMission | undefined {
  return ALL_STORY_MISSIONS.find((m) => m.id === id);
}

export function getStoryMissionsByAct(act: 1 | 2 | 3): StoryMission[] {
  if (act === 1) return ACT_I_STORY_MISSIONS;
  if (act === 2) return ACT_II_STORY_MISSIONS;
  return ACT_III_STORY_MISSIONS;
}

export function getStoryMissions(): StoryMission[] {
  return ALL_STORY_MISSIONS;
}
